import Head from "next/head";
import { OGLoginContent } from "../../components/organisms/content/login-content.organism";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quản lý luận văn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OGLoginContent />
    </>
  );
}
