import { Layout } from "antd";
import Head from "next/head";
import { OGAdminContent } from "../../components/organisms/content/admin-content.organism";
import { OGHeader } from "../../components/organisms/header/header.organism";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quản lý luận văn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Content className="overflow-hidden h-screen">
        <OGHeader />
        <OGAdminContent />
      </Layout.Content>
    </>
  );
}
