import { Layout } from "antd";
import Head from "next/head";
import { OGScheduleContent } from "../../components/organisms/content/schedule-content.organism";
import { OGHeader } from "../../components/organisms/header/header.organism";
import { Roles } from "../../constants/enums";
import { useMount } from "../../hooks/use-mount";
import { useRecoilValue } from "recoil";
import { userState } from "../../stores/auth.store";
import { User } from "../../interfaces/user.interface";

const { Content } = Layout;
export default function Home() {
  const mount = useMount();
  const user = useRecoilValue<User | null>(userState);

  return (
    mount &&
    user && (
      <>
        <Head>
          <title>Quản lý luận văn</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Content className="min-h-screen bg-gray-100">
          <OGHeader />
          <OGScheduleContent
            role={
              user.roles.includes(Roles.TEACHER) ? Roles.TEACHER : Roles.STUDENT
            }
          />
        </Content>
      </>
    )
  );
}
