import { Layout } from "antd";
import Head from "next/head";
import { OGHeader } from "../components/organisms/header/header.organism";
import { OGStudentTable } from "../components/organisms/table/student-table.organism";
import { OGTeacherTable } from "../components/organisms/table/teacher-table.organism";
import { isTeacher } from "../utils/role.util";

const { Content } = Layout;
export default function Home() {

  return (
    <>
      <Head>
        <title>Quản lý luận văn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content className="min-h-screen bg-gray-100">
        <OGHeader />
        <Content className="my-5">
          {isTeacher() ? <OGStudentTable /> : <OGTeacherTable />}
        </Content>
      </Content>
    </>
  );
}
