import { Layout } from "antd";
import Head from "next/head";
import { OGHeader } from "../components/organisms/header/header.organism";
import { OGTable } from "../components/organisms/table/table.organism";
import { teacherListConfig } from "../config/student/teacher-list-config";
import { studentListConfig } from "../config/teacher/student-list.config";
import { isTeacher } from "../utils/role.util";

const { Content } = Layout;
export default function Home() {
  return (
    <>
      <Head>
        <title>Quản lý luận văn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content className="min-h-screen bg-gray-100">
        <OGHeader />
        <Content className="mx-20 my-5">
          <OGTable
            config={isTeacher() ? studentListConfig : teacherListConfig}
          />
        </Content>
      </Content>
    </>
  );
}
