import { Layout } from "antd";
import Head from "next/head";
import { OGHeader } from "../components/organisms/header/header.organism";
import { OGTeacherTable } from "../components/organisms/table/teacher-table.organism";

export default function Home() {
  const { Content, Header } = Layout;

  return (
    <>
      <Head>
        <title>Quản lý luận văn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content className="h-screen bg-gray-100">
        <OGHeader />
        <Content className="mt-16">
          <OGTeacherTable />
        </Content>
      </Content>
    </>
  );
}
